"""
FastAPI router: CVE Image Registry.

Endpoints (exactly as specified):
    POST   /registry
    GET    /registry
    PUT    /registry/{id}
    DELETE /registry/{id}

Commit/rollback of the underlying transaction is owned by the shared
`core.database.get_db_session` dependency (per module scope, the database
layer already exists elsewhere in the project). This router only flushes
via the service/repository layers so autogenerated PKs are available in
responses.
"""

from __future__ import annotations

from typing import List, Optional

import structlog
from fastapi import APIRouter, Depends, HTTPException, Query, status

from twin_generator.api.deps import get_registry_service
from twin_generator.registry.service import RegistryService
from twin_generator.schemas.twin_registry import (
    RegistryEntryCreate,
    RegistryEntryRead,
    RegistryEntryUpdate,
)
from twin_generator.utils.exceptions import DuplicateRegistryEntryError, RegistryEntryNotFoundError

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/registry", tags=["CVE Image Registry"])


@router.post(
    "",
    response_model=RegistryEntryRead,
    status_code=status.HTTP_201_CREATED,
)
def create_registry_entry(
    payload: RegistryEntryCreate,
    service: RegistryService = Depends(get_registry_service),
) -> RegistryEntryRead:
    """Create a CVE -> image mapping.

    Returns HTTP 409 when the same CVE/image/version mapping already exists.
    """
    try:
        entry = service.create_entry(payload)
    except DuplicateRegistryEntryError as exc:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=str(exc),
        ) from exc

    return RegistryEntryRead.model_validate(entry)

@router.get("", response_model=List[RegistryEntryRead])
def list_registry_entries(
    cve: Optional[str] = Query(None, description="Filter mappings to a single CVE."),
    service: RegistryService = Depends(get_registry_service),
) -> List[RegistryEntryRead]:
    """List all CVE -> image mappings, optionally filtered by CVE."""
    entries = service.list_entries(cve=cve)
    return [RegistryEntryRead.model_validate(e) for e in entries]


@router.put("/{entry_id}", response_model=RegistryEntryRead)
def update_registry_entry(
    entry_id: int,
    payload: RegistryEntryUpdate,
    service: RegistryService = Depends(get_registry_service),
) -> RegistryEntryRead:
    """Update an existing mapping. Unset fields are left unchanged."""
    try:
        entry = service.update_entry(entry_id, payload)
    except RegistryEntryNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    return RegistryEntryRead.model_validate(entry)


@router.delete(
    "/{entry_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_model=None,
)
def delete_registry_entry(
    entry_id: int,
    service: RegistryService = Depends(get_registry_service),
) -> None:
    """Remove a mapping from the registry."""
    try:
        service.delete_entry(entry_id)
    except RegistryEntryNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
